/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertAdult: typeof import('./src/components/AlertAdult.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonDefault: typeof import('./src/components/ButtonDefault.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Foooter: typeof import('./src/components/Foooter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterDefault: typeof import('./src/components/FooterDefault.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
